# Generated by Django 4.2.7 on 2023-12-19 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('System_Change_Request', 'System_Change_Request'), ('System_Bug', 'System_Bug'), ('General', 'General'), ('Ad_Hoc_Requests', 'Ad_Hoc_Requests'), ('Routine_Tasks', 'Routine_Tasks')], default='General', max_length=255)),
                ('subcat', models.CharField(choices=[('Module_A', 'Module_A'), ('Module_B', 'Module_B'), ('Module_C', 'Module_C'), ('Module_D', 'Module_D')], default='Module_A', max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=255)),
                ('due_date', models.DateField(default=posts.models.Post.get_deadline)),
                ('title', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Working_In_Progress', 'Working_In_Progress'), ('Pending_Review', 'Pending_Review'), ('Pending_Approve', 'Pending_Approve'), ('Completed', 'Completed'), ('Request_To_Cancel', 'Request_To_Cancel'), ('Cancelled', 'Cancelled'), ('Request_To_Reopen', 'Request_To_Reopen')], default='New', max_length=255)),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_approver', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_requester', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_created_by', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.post')),
            ],
        ),
    ]
