# Generated by Django 4.2.7 on 2023-12-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_actionitem_comment_post_post_general_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
