# Generated by Django 4.2.7 on 2023-12-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_comment_options_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylog',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='post',
            name='flag_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
