# Generated by Django 4.2.7 on 2023-11-19 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QClog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_1', models.CharField(choices=[('Actual', 'Actual'), ('Shadow_1', 'Shadow_1'), ('Shadow_2', 'Shadow_2'), ('Shadow_3', 'Shadow_3'), ('Shadow_test', 'Shadow_test')], default='Actual', max_length=255)),
                ('role_2', models.CharField(choices=[('Actual', 'Actual'), ('Shadow_1', 'Shadow_1'), ('Shadow_2', 'Shadow_2'), ('Shadow_3', 'Shadow_3'), ('Shadow_test', 'Shadow_test')], default='Shadow_1', max_length=255)),
                ('qcfile', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_one', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_two', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_three', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_four', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_five', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('first_letter', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=255)),
                ('attribute_one', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_two', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_three', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_four', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_five', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_country', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_country', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_one', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_two', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_three', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_four', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_five', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='operations.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignment', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_assignment', to=settings.AUTH_USER_MODEL)),
                ('role_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_actual', to=settings.AUTH_USER_MODEL)),
                ('role_s_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_s_one', to=settings.AUTH_USER_MODEL)),
                ('role_s_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_s_test', to=settings.AUTH_USER_MODEL)),
                ('role_s_three', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_s_three', to=settings.AUTH_USER_MODEL)),
                ('role_s_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_s_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
