# Generated by Django 4.2.7 on 2023-11-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_assignment_country_assignment_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='country',
        ),
        migrations.AddField(
            model_name='assignment',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='operations.country'),
            preserve_default=False,
        ),
    ]
