# Generated by Django 4.2.7 on 2023-11-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_qclog_qcresult_alter_assignment_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qclognote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='qclognote',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='qclognote',
            name='qclog',
        ),
        migrations.AddField(
            model_name='qclog',
            name='qclognote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qclognote', to='operations.qclognote'),
        ),
    ]
