# Generated by Django 4.2.7 on 2023-11-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_remove_qclognote_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcticket',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_country', to='operations.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_country', to='operations.country'),
        ),
    ]
