# Generated by Django 4.2.7 on 2023-11-26 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0007_qcticket_country_alter_assignment_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qclog',
            name='each_qcfile',
        ),
        migrations.RemoveField(
            model_name='qclog',
            name='mistaked_made_by',
        ),
        migrations.RemoveField(
            model_name='qclog',
            name='qclognote',
        ),
        migrations.RemoveField(
            model_name='qclog',
            name='qcresult',
        ),
        migrations.RemoveField(
            model_name='qclog',
            name='status',
        ),
        migrations.AddField(
            model_name='qclog',
            name='action',
            field=models.CharField(choices=[('Submit_Ticket', 'Submit_Ticket'), ('Running_By_Script', 'Running_By_Script'), ('Completed_By_Script', 'Completed_By_Script')], default='log_action', max_length=255),
        ),
        migrations.AddField(
            model_name='qcticket',
            name='mistaked_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_qclog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcticket',
            name='qclognote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qclognote', to='operations.qclognote'),
        ),
        migrations.AddField(
            model_name='qcticket',
            name='qcresult',
            field=models.CharField(choices=[('No_Error', 'No_Error'), ('Has_Error', 'Has_Error')], default='No_Error', max_length=255),
        ),
        migrations.AddField(
            model_name='qcticket',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending_Update', 'Pending_Update'), ('Pending_Approve', 'Pending_Approve'), ('Submit_To_Cancel', 'Submit_To_Cancel'), ('Cancelled_Approved', 'Cancelled_Approved')], default='Completed', max_length=255),
        ),
    ]
