# Generated by Django 4.2.7 on 2023-11-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_qclog_each_qcfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcticket',
            name='qcresult',
            field=models.CharField(blank=True, choices=[('No_Error', 'No_Error'), ('Has_Error', 'Has_Error')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qcticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending_Update', 'Pending_Update'), ('Pending_Approve', 'Pending_Approve'), ('Submit_To_Cancel', 'Submit_To_Cancel'), ('Cancelled_Approved', 'Cancelled_Approved')], max_length=255, null=True),
        ),
    ]
