# Generated by Django 4.2.7 on 2023-11-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_qcticket_qcresult_alter_qcticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcticket',
            name='qclognote',
        ),
        migrations.AlterField(
            model_name='qclognote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_note', to='operations.qcticket'),
        ),
        migrations.AlterField(
            model_name='qcticket',
            name='status',
            field=models.CharField(choices=[('In_Queue', 'In_Queue'), ('Completed', 'Completed'), ('Pending_Update', 'Pending_Update'), ('Pending_Approve', 'Pending_Approve'), ('Submit_To_Cancel', 'Submit_To_Cancel'), ('Cancelled_Approved', 'Cancelled_Approved')], default='In_Queue', max_length=255),
        ),
    ]
