# Generated by Django 4.2.7 on 2023-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_remove_qcticket_qclognote_alter_qclognote_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qclognote',
            name='note_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
