# Generated by Django 4.2.7 on 2023-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_qclognote_note_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcticket',
            name='flag_script_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qcticket',
            name='status',
            field=models.CharField(choices=[('In_Queue', 'In_Queue'), ('Completed', 'Completed')], default='In_Queue', max_length=255),
        ),
    ]
