# Generated by Django 4.2.7 on 2023-12-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_qcticket_flag_script_process_alter_qcticket_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['short_name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='qclog',
            options={'verbose_name_plural': 'QcLogs'},
        ),
        migrations.AlterModelOptions(
            name='qclognote',
            options={'ordering': ['-id'], 'verbose_name_plural': 'QcLogNotes'},
        ),
        migrations.AlterModelOptions(
            name='qcticket',
            options={'verbose_name_plural': 'QcTickets'},
        ),
    ]
